### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by politicus** [danielbayley/homebrew-alfred#1]
How can I use homebrew-alfred once it is installed?

**Comment by danielbayley** [comment]
@politicus The instructions are right there in [the README](https://github.com/danielbayley/homebrew-alfred#install):

> ~~~ sh
> brew tap danielbayley/alfred
> brew cask install #workflow
> ~~~
Where `#workflow` is any of the Alfred workflows in [Casks/]. Feel free to submit PRs for other workflows… or maintain your own _[tap]_.

Soon there will also be _[awm]_… a wrapper around this [tap] with a CLI to help with workflow development.

[Casks/]: https://github.com/danielbayley/homebrew-alfred/tree/master/Casks
[tap]: https://docs.brew.sh/Taps
[awm]: https://github.com/danielbayley/awm
