### ISSUE TITLE
Error: Unknown command: cask

### ISSUE THREAD

**Issue by tbrodbeck** [danielbayley/homebrew-alfred#9]
Hi this is a very cool idea I really want to try it out. Unfortunately, it does not work with the newest version of homebrew since they deprecated the `cask` argument.

```brew alfred install
Error: Unknown command: cask
```

Probably a fix would be as easy as changing
```
`exec "brew", "cask", *args`
```
to 
```
`exec "brew", *args, "--cask"`
```

**Comment by danielbayley** [comment]
@tbrodbeck Should work now… please test. Thanks!

**Comment by tbrodbeck** [comment]
Works. Merci!
